### ISSUE TITLE
salsa.debian.org GitLab URLs not accessible

### ISSUE THREAD

**Issue by abhiranjeet** [Azure/sonic-buildimage#10097]
#### Description
Looks like salsa.debian.org GitLab is not responding. There are multiple GitLab URLs which are being used to build debian packages for SONiC (monit, openssh, etc.). This was working till yesterday.

#### Steps to reproduce the issue:
1. Build any SONiC Image

#### Describe the results you received:
```
Cloning into 'openssh-server'...
remote: GitLab is not responding
fatal: unable to access 'https://salsa.debian.org/ssh-team/openssh.git/': The requested URL returned error: 502
make[1]: *** [Makefile:9: /sonic/target/debs/buster/openssh-server_7.9p1-10+deb10u2_amd64.deb] Error 128
make[1]: Leaving directory '/sonic/src/openssh'
[  FAIL LOG END  ] [ target/debs/buster/openssh-server_7.9p1-10+deb10u2_amd64.deb ]
```

#### Describe the results you expected:
Example: I expected openssh-server deb package to be built. But this issue is not limited to openssh. Other deb packages which use salsa.debian.org URL, are not working at all. Even tried accessing GUI of GitLab
![image](https://user-images.githubusercontent.com/65591112/155890169-a2af2d61-74e8-48ee-9e67-af0aa85a362d.png)

**Comment by DesktopECHO** [comment]
[https://micronews.debian.org/2022/1645992519.html](https://micronews.debian.org/2022/1645992519.html)

**Comment by mfyuce** [comment]
Any salsa mirror you know of?

**Comment by hubblezzhu** [comment]
Can't do anything but wait?

**Comment by SamB** [comment]
> Can't do anything but wait?

I suppose you could try asking nicely on #salsa (<irc://irc.debian.org/salsa>) whether it would be worth putting up a read-only git mirror in salsa's place. (Assuming they haven't done that already?)

Also, there are of course source packages available in the Debian archive and at https://snapshot.debian.org/ -- for example, just now I went to snapshot.debian.org and entered `openssh-server` into the **binary package** search box, which took me to <https://snapshot.debian.org/binary/openssh-server/>. On that page, I then searched for the version number in your error message above, `7.9p1-10:2b:deb10u2`, which matched a single line, taking me to: <https://snapshot.debian.org/package/openssh/1%3A7.9p1-10%2Bdeb10u2/#openssh-server_1:3a:7.9p1-10:2b:deb10u2>.

Now here's the tricky part (well, *I* found it tricky): you **scroll up to the top**. Next, copy the URL from a `.dsc` ([Debian source control file](https://www.debian.org/doc/debian-policy/ch-controlfields.html#debian-source-control-files-dsc), essentially a manifest) link, and you can then, for example, download and unpack the source package with `dget` (from `devscripts`) as follows:

```
$ dget https://snapshot.debian.org/archive/debian/20200202T210747Z/pool/main/o/openssh/openssh_7.9p1-10%2Bdeb10u2.dsc
[dget downloads 4 files, checks the signature on the `.dsc` file, then invokes dpkg-source to unpack the package and apply the patches]
$ ls -ld openssh*
drwxr-xr-x 7 naesten naesten   12288 Mar  1 16:35 openssh-7.9p1
-rw-r--r-- 1 naesten naesten    3321 Mar  1 16:35 openssh_7.9p1-10%2Bdeb10u2.dsc
-rw-r--r-- 1 naesten naesten  174016 Mar  1 16:35 openssh_7.9p1-10+deb10u2.debian.tar.xz
-rw-r--r-- 1 naesten naesten 1565384 Mar  1 16:35 openssh_7.9p1.orig.tar.gz
-rw-r--r-- 1 naesten naesten     683 Mar  1 16:35 openssh_7.9p1.orig.tar.gz.asc
$
```

I'm not sure how hard this would be to use in your build process, but the service is ... mostly reliable; if you look at <https://snapshot.debian.org>, you'll see that it's been working fairly well since it became an official Debian service in 2010; occasionally imports will fall over for a while, but apparently they've been serving existing files just fine for the past 12 years.

-----

p.s. The version didn't quite match due to an epoch, defined in the [policy manual](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version) as:

<blockquote>
<dl>
<dt><code>epoch</code></dt><dd><p>This is a single (generally small) unsigned integer. It may be
omitted, in which case zero is assumed.</p>
<p>Epochs can help when the upstream version numbering scheme
changes, but they must be used with care.  You should not change
the epoch, even in experimental, without getting consensus on
debian-devel first.</p>
</dd>
</dl>
</blockquote>

Clarified [further down](https://www.debian.org/doc/debian-policy/ch-controlfields.html#epochs-should-be-used-sparingly):

<blockquote>
Note that the purpose of epochs is to cope with situations where the upstream version numbering scheme changes and to allow us to leave behind serious mistakes.
</blockquote>

It is treated as the most significant part of a version in the comparison algorithm. 

p.p.s. If you're wondering why I've gone to all this effort, well, I ... didn't realize what org this was, and that you're surely capable of figuring out how to use snapshots.debian.org on your own ...

**Comment by zhangyanzhao** [comment]
Server issue impacted others as well.

**Comment by vincent201881** [comment]
now, it seem still not work? anyone knows why? 
Cloning into 'tmp'...
fatal: unable to access 'https://salsa.debian.org/debian/libteam.git/': Failed to connect to salsa.debian.org port 443: Connection timed out

**Comment by DesktopECHO** [comment]
[https://salsa.debian.org](https://salsa.debian.org/) has been down for the last 12 hours.
Any projects that depend on Salsa are in-op until Debian fixes whatever is messed-up with the site.
