### ISSUE TITLE
Per Vlan DHCP relay is broken if DHCP server is connected via Vlan interface

### ISSUE THREAD

**Issue by johcheun** [Azure/sonic-buildimage#1247]
**Description**
Prior to the per vlan dhcp relay support was added via https://github.com/Azure/sonic-buildimage/commit/1d16a37d48fcee31f81897a6dff8c83e8bed8851 , DhcpResources tag was used to specify the Dhcp relay server information, and all routed interfaces, VLAN interfaces and Port-Channel interfaces were added to listening interfaces for the dhcrelay command in the j2 template.

After the commit with the new DhcpRelay tag, only the dhcp relay vlan, routed interfaces and Port-Channel interfaces are added to the dhcrelay command, but if the dhcp server sits behind a different vlan, the dhcp offer is not getting forwarded. 

**Steps to reproduce the issue:**
1. Configure per vlan dhcp relay
2. Have a dhcp server connected to a VLAN interface in the topology
3. Have dhcp relay configured on another VLAN interface.

**Describe the results you received:**
DHCP request is getting forwarded to the dhcp server, but DHCP offer received from the server is dropped since it is not in the dhcrelay listening interfaces. 

**Describe the results you expected:**
DHCP offer should be forwarded properly in the case of dhcp server connected to vlan interface.

**Additional information you deem important (e.g. issue happens only occasionally):**
Manually modified docker-dhcp-relay.supervisord.conf to include the dhcp server VLAN, and dhcp relay is working properly.

**Comment by jleveque** [comment]
Hi @johcheun. We have moved to a DHCP-relay-per-VLAN model in order to support specifying a different set of DHCP servers for servers under each VLAN. This allows for DHCP traffic to only travel between the appropriate clients and servers. This configuration assumes all DHCP servers are reachable via uplink interfaces. We have not encountered the scenario where a DHCP server(s) resides under antoher VLAN of the same switch.

The best solution I can think of to support both scenarios is to be able to specify on which interfaces the relay should listen for requests from clients (downstream interfaces) and which interfaces to listen for replies from DHCP servers (upstream interfaces). With this functionality, the one VLAN containing DHCP clients can be specified as a downstream interface and all other interfaces, including other VLANs can be specified as upstream interfaces.

Unfortunately, the version of isc-dhcp-relay that we are currently using (v4.3.3-6) does not support specifying whether an IPv4 interface is an upstream or downstream interface. All interfaces specified using the `-i` parameter are listened on for both requests and replies. But I just looked into upstream source of isc-dhcp-relay, and it appears they have since added the ability to specify upstream (`-iu`) and downstream (`-id`) v4 interfaces. Unfortunately, all versions > v4.3.3-6 require dependency packages that are not available in Debian Jessie, so we currently cannot compile or install a newer version.

That said, we are targeting upgrading the underlying SONiC distro from Debian Jessie to Debian Stretch for our 03/15/18 release, at which time we will be able to upgrade to the latest version of isc-dhcp-relay which will offer this support. Hopefully this timeline is reasonable for you, since you seem to have a simple workaround in the meantime.

**Comment by jleveque** [comment]
Hi @johcheun. We have moved to a DHCP-relay-per-VLAN model in order to support specifying a different set of DHCP servers for servers under each VLAN. This allows for DHCP traffic to only travel between the appropriate clients and servers. This configuration assumes all DHCP servers are reachable via uplink interfaces. We have not encountered the scenario where a DHCP server(s) resides under antoher VLAN of the same switch.

The best solution I can think of to support both scenarios is to be able to specify on which interfaces the relay should listen for requests from clients (downstream interfaces) and which interfaces to listen for replies from DHCP servers (upstream interfaces). With this functionality, the one VLAN containing DHCP clients can be specified as a downstream interface and all other interfaces, including other VLANs can be specified as upstream interfaces.

Unfortunately, the version of isc-dhcp-relay that we are currently using (v4.3.3-6) does not support specifying whether an IPv4 interface is an upstream or downstream interface. All interfaces specified using the `-i` parameter are listened on for both requests and replies. But I just looked into upstream source of isc-dhcp-relay, and it appears they have since added the ability to specify upstream (`-iu`) and downstream (`-id`) v4 interfaces. Unfortunately, all versions > v4.3.3-6 require dependency packages that are not available in Debian Jessie, so we currently cannot compile or install a newer version.

That said, we are targeting upgrading the underlying SONiC distro from Debian Jessie to Debian Stretch for our 03/15/18 release, at which time we will be able to upgrade to the latest version of isc-dhcp-relay which will offer this support. Hopefully this timeline is reasonable for you, since you seem to have a simple workaround in the meantime.

**Comment by johcheun** [comment]
@jleveque Sounds good.  Actually with the flexibility of specifying upstream / downstream dhcp port, it could further eliminate unwanted dhcp traffic to other segments of the network.  Thanks.

**Comment by jleveque** [comment]
Closed as this is resolved by the following commits on the respective branches:
- master: https://github.com/Azure/sonic-buildimage/pull/2946
- 201811: https://github.com/Azure/sonic-buildimage/pull/2919
- 201803: https://github.com/Azure/sonic-buildimage/pull/2857
