### ISSUE TITLE
[minigraph.py] Crashes upon <DhcpRelays></DhcpRelays> in VlanInterface section

### ISSUE THREAD

**Issue by taoyl-ms** [Azure/sonic-buildimage#1302]
**Description**
In minigraph.py:
```
            if vintf.find(str(QName(ns, "DhcpRelays"))) is not None:
                vintfdhcpservers = vintf.find(str(QName(ns, "DhcpRelays"))).text
                vdhcpserver_list = vintfdhcpservers.split(';')
                vlan_attributes['dhcp_servers'] = vdhcpserver_list

```
This will crash upon case of `<DhcpRelays></DhcpRelays>`, i.e. `vintf.find(str(QName(ns, "DhcpRelays"))) is not None` but `vintf.find(str(QName(ns, "DhcpRelays"))).text is None`.

**Steps to reproduce the issue:**
Create a minigraph with `<DhcpRelays></DhcpRelays>` in `<VlanInterface>` section, then `sonic-cfggen -m`.

**Comment by jleveque** [comment]
I feel like the scope of this issue is larger than just the `<DhcpRelays></DhcpRelays>` tag, and could pose an issue with any tag without data. I think we should either:

a.) Explicitly not allow empty tags (therefore undefined behavior is acceptable)

OR

b.) Add support throughout minigraph.py to gracefully handle empty tags.

**Comment by lguohan** [comment]
option ```b``` is preferred.

**Comment by pavel-shirshov** [comment]
Fixed in https://github.com/Azure/sonic-buildimage/pull/2154
