### ISSUE TITLE
Execute  ”make configure PLATFORM=centec” get some error.

### ISSUE THREAD

**Issue by wjf1993** [Azure/sonic-buildimage#1622]
sonic@ubuntu:/home/sdn/sonic/sonic-buildimage$ make configure PLATFORM=centec     
Image sonic-slave-base:39eae091d5a not found. Building...
Sending build context to Docker daemon 11.78 kB
Step 1/27 : FROM debian:jessie
jessie: Pulling from library/debian
f2b6b4884fc8: Pulling fs layer 
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/5d/5dd74d62fab80c6c7c01ea38288fde8b011bc79a82198ebb145d6bcb09ceddd2/data?Expires=1524151537&Signature=PoCh2Ro7oqgfr2-cBPQcXXiKomwDGmzP~T4e~FqWAnid7EVN-zZazWOgVZ7U39JxQcKIZPDFz6B6rZYhNZTeWdKIC-erIke-KNMzWfytVGJm5gpfUp-qz85odddvWca0ueLH4O3k29boIENyJ8GzecQ9B-Yo70-g4OSZiiAo2lg_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
Makefile:81: recipe for target 'configure' failed
make: *** [configure] Error 1

It seems some network issue of getting things from the internet.
How to solve this issue？set proxy ？
thank

**Comment by yangbashuang** [comment]
this is should be a network issus, can use proxy to make again, eg:
http_proxy=http://192.169.25.29:3128 https_proxy://192.168.25.29:3128 make configure PLATFORM=centec
http_proxy=http://192.169.25.29:3128 https_proxy://192.168.25.29:3128 make 

currentlly centec platform still got build errors from sairedis, because libsai have not been updated to 1.2.4, but we are working on it

**Comment by yangbashuang** [comment]
see https://github.com/Azure/sonic-buildimage/blob/master/README.md:

Use http_proxy=[your_proxy] https_proxy=[your_proxy] make to enable http(s) proxy in the build process.

**Comment by wjf1993** [comment]
@yangbashuang Thankyou，xiexie.
