### ISSUE TITLE
Get into sonic-slave docker

### ISSUE THREAD

**Issue by wendani** [Azure/sonic-buildimage#2029]
**Description**
make KEEP_SLAVE_ON=yes SOURCE_FOLDER=/home/localadmin target/sonic-aboot-broadcom.swi

does not get into the slave docker for kernel 4.9.0-7-amd64

**Steps to reproduce the issue:**
1. make target/sonic-aboot-broadcom.swi
2. make KEEP_SLAVE_ON=yes SOURCE_FOLDER=/home/localadmin target/sonic-aboot-broadcom.swi
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
This is a known issue with stretch build.

The reason we want to keep slave on is usually because we want to build something incrementally, or retry quickly.

With stretch, one has to be consciously know which slave docker to keep:

If the intention is to stay in the stretch docker, then issue "make stretch KEEP_SLAVE_ON=yes"
If the intention is to stay in the jessy docker, then issue "make stretch" to complete stretch build first, then issue "make NOSTETCH=1 KEEP_SLAVE_ON=yes [target] to stay in the jessy docker.

This is an interim inconvenience until we move all dockers to stretch. It might be better fixed with updating document than fixing the make file itself.

Cheers,
Ying

**Comment by wendani** [comment]
Which docker shall I choose if I build the opennsl and saibcm?

**Comment by nikos-github** [comment]
@wendani If I'm not mistaken, the point being made above is illustrating how to keep the slave docker on when you use stretch (the default), and when you use jessie (the non-default). Chances are you are building using the default (stretch), so I would follow that.

**Comment by yxieca** [comment]
@wendani For current Broadcom SAI release 3.1, you want to stay on Jessie docker for the build. And you don't want to use 4.9 kernel headers, you want to use 3.16 kernel headers. So it makes more sense for you to use an older branch, e.g. 201803 for this purpose.

**Comment by wendani** [comment]
@yxieca Thanks I have problem building opennsl 3.4.1.11-1 (failed), which uses linux headers 3.16.0-4. However, I donot have 3.16.0-4 header pkg in the target/debs.

**Comment by yxieca** [comment]
@wendani You can copy the header files from Jenkins, like 201803 build. Or you can start you build from 201803 branch.
