### ISSUE TITLE
tags 201811-1 seems to be rebased，it's commit id 602204f cannot be found in both master and 201811 branch

### ISSUE THREAD

**Issue by TencentSwitchGroup** [Azure/sonic-buildimage#2492]
**Description**

Cannot find commit [602204f](https://github.com/Azure/sonic-buildimage/commit/602204f54e9325842735b327458fa8a2963d483b) (tags 201811-1) in both branch master and 201811. It seems there's a `git rebase` after the tag. 

After compare log, I think the new commit id of tags 201811-1 should be [1e8d3ec](https://github.com/Azure/sonic-buildimage/commit/1e8d3ec156899e0d3e4af3cc87bf4399a0dce948). 

Please release 201811-1 with the new commit id.

**Comment by yxieca** [comment]
That is correct. There was an PR went into 201811 branch by mistake. And the change went later into master branch. Then cherry-picked again from master branch. In order to do so, the previous commit was discarded.

201811-01 was a work tag just so that I have a log for what was done before rebase. Please ignore this tag and use latest 201811 branch instead.

**Comment by xinliu-seattle** [comment]
Ying will delete the tag which is a mistake, and close the issue.

**Comment by yxieca** [comment]
The tag has been removed.
