### ISSUE TITLE
Portchannel with subinterfaces lead to orchagent crash

### ISSUE THREAD

**Issue by mkovnir** [Azure/sonic-buildimage#4142]
**Description**

Orchagent crash if configuration contain Portchannel in routed mode with subinterfaces.

**Steps to reproduce the issue:**
1.  Apply the following sample configuration:
```
{
"VLAN_SUB_INTERFACE": {
        "PortChannel2.21": {  "admin_status": "up" }, 
        "PortChannel2.21|198.18.21.10/30": {}
    }
} 
```

**Describe the results you received:**
After configuration apply orchagent crashs and the following errors are appear in syslog:
```
NOTICE swss#orchagent: :- addSubPort: Sub interface PortChannel2.21 inherits mtu size 9100 from parent port PortChannel2
ERR swss#orchagent: :- meta_generic_validation_objlist: SAI_ROUTER_INTERFACE_ATTR_PORT_ID:SAI_ATTR_VALUE_TYPE_OBJECT_ID object on list [0] is NULL, but not allowed
ERR swss#orchagent: :- addRouterIntfs: Failed to create router interface PortChannel2.21, rv:-5
INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::runtime_error'
INFO swss#supervisord: orchagent   what():  Failed to create router interface.
INFO swss#supervisor-proc-exit-listener: Process orchagent exited unxepectedly. Terminating supervisor...
```

**Describe the results you expected:**
Portchannel with subinterfaces should be created, same as Ethernet with subinterfaces.

**Comment by wendani** [comment]
Thanks for reporting the issue. I just noticed your post.
I believe the problem is here: https://github.com/Azure/sonic-swss/blob/master/orchagent/portsorch.cpp#L617

When adding the parent port oid, we did not check the type of the parent port, whether it is of type PORT (physical port) or LAG (port channel). This should cause the sairedis metadata validation to fail.
