### ISSUE TITLE
[swss] 'oper_status' attribute can have a value of '2'?

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#456]
The 'oper_status' attribute of a port in our DB has three potential values: 'up', 'down' and '2'.

Can reproduce on a T0 setup. Simply 'ifdown' a port that's part of the VLAN. Reading the database rapidly, you will see the 'oper_status' change from 'up' to 'down' and then quickly to '2', where it will stay.

Likewise, bringing the port back up using 'ifup', you will see the 'oper_status' change from '2' to 'down' and then to 'up'.

**Comment by stcheng** [comment]
This happens because currently both portsyncd and orchagent are updating this field simultaneously. When a port oper_status changes, ASIC will send port_status_change notification as well as kernel will send netlink message. Because in orchagent code, there is no mapping between the enum and the string, 2 is not converted to 'down' and it causes this bug.

In order to fix this issue, only portsyncd's update logic is needed to override the current status of a port in APP_DB.

**Comment by lguohan** [comment]
is this resolved?

**Comment by stcheng** [comment]
yes. resolved. i'll update the swss submodule.
