### ISSUE TITLE
Multiple tests fail because of syncd process_on_fdb_event message

### ISSUE THREAD

**Issue by theasianpianist** [Azure/sonic-buildimage#5616]
**Description**

**Steps to reproduce the issue:**
1. Run a set of nightly test cases

**Describe the results you received:**
Multiple instances of LogAnalyzer errors with messages like the following:
```
'Oct 13 05:11:35.253670 sonic ERR syncd#syncd: :- process_on_fdb_event: FDB notification was not sent since it contain invalid OIDs, bug?\n'
```

**Describe the results you expected:**
Test passes

**Additional information you deem important (e.g. issue happens only occasionally):**
```
SONiC Software Version: SONiC.master.441-5e97574e
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 5e97574e
Build date: Sun Oct 11 06:44:53 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-C32
ASIC: broadcom
Serial Number: JPE20033081
Uptime: 19:19:51 up  9:29,  2 users,  load average: 0.42, 0.86, 1.12

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                0618f9d183ca        394MB
docker-teamd                  master.441-5e97574e   0618f9d183ca        394MB
docker-sonic-mgmt-framework   latest                25ed63a1f116        486MB
docker-sonic-mgmt-framework   master.441-5e97574e   25ed63a1f116        486MB
docker-router-advertiser      latest                915797355232        359MB
docker-router-advertiser      master.441-5e97574e   915797355232        359MB
docker-platform-monitor       latest                60c0a1efba18        441MB
docker-platform-monitor       master.441-5e97574e   60c0a1efba18        441MB
docker-lldp                   latest                d2c749b8d824        388MB
docker-lldp                   master.441-5e97574e   d2c749b8d824        388MB
docker-dhcp-relay             latest                19c03a62b26b        366MB
docker-dhcp-relay             master.441-5e97574e   19c03a62b26b        366MB
docker-database               latest                acf3a638c60b        359MB
docker-database               master.441-5e97574e   acf3a638c60b        359MB
docker-orchagent              latest                e910702542a6        407MB
docker-orchagent              master.441-5e97574e   e910702542a6        407MB
docker-nat                    latest                5bf7bf09f796        396MB
docker-nat                    master.441-5e97574e   5bf7bf09f796        396MB
docker-sonic-telemetry        latest                d3945a20829f        429MB
docker-sonic-telemetry        master.441-5e97574e   d3945a20829f        429MB
docker-fpm-frr                latest                341b448c3242        410MB
docker-fpm-frr                master.441-5e97574e   341b448c3242        410MB
docker-sflow                  latest                0e12a8f57e38        397MB
docker-sflow                  master.441-5e97574e   0e12a8f57e38        397MB
docker-snmp                   latest                ae7ec1512b58        399MB
docker-snmp                   master.441-5e97574e   ae7ec1512b58        399MB
docker-syncd-brcm             latest                28de685e97ed        542MB
docker-syncd-brcm             master.441-5e97574e   28de685e97ed        542MB
```

**Comment by daall** [comment]
@theasianpianist can you please provide @kcudnik with the logs + sairedis recordings for this issue?

**Comment by kcudnik** [comment]
got logs, will analyze

**Comment by kcudnik** [comment]
i did analysis and posted results internally, let me know if you want them to see here as well

**Comment by kcudnik** [comment]
Iif we look at syslog, then we can see *a lot* of  messages from internal bcm:
Oct 13 06:33:25.529002 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 1 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x2d lagid:0x0 flags:0x10440 flags2:0x0 lag:false
Oct 13 06:33:25.545438 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 0 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x0 lagid:0x0 flags:0x9f4468 flags2:0x0 lag:false
Oct 13 06:33:25.545438 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 1 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x39 lagid:0x0 flags:0x1f0440 flags2:0x0 lag:false

This particular mac address is jumping from port to port like over 20 times per second, in syslog you attached, during 2.5min time span, this message pops up 9500 times!
Is that part of the unittest ? or could be some switch/sai internal issue ?

Then we can see about 4500 logs like this:
Oct 13 06:33:26.622762 str2-7050cx3-acs-01 WARNING syncd#syncd: :- check_fdb_event_notification_data: RID 0x1003a00000000 on SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID is not present on local ASIC DB

Each fdb_event notification syncd will receive, it checks all OIDs (RIDs) in that notifications, if every RID is present in Redis database, this means whether it was previously created or discovered,
Here, RID value (0x1003a00000000) which is in all notification, is not present in redis db, or was discovered, value 0x3a in oid suggest that this item is dec 58, SAI_OBJECT_TYPE_BRIDGE_PORT
Here it would be helpful to have dump on VIDTORID table from redis database with this command:
redis-cli -n 1 "hgetall" "RIDTOVID"
so we could see what are defined RID values for bridge ports, and to see/figure out whether actual value 0x1003a00000000 is correct,

Three also sylog limit kicked in:
Oct 13 06:34:41.014333 str2-7050cx3-acs-01 INFO syncd#rsyslogd: imuxsock[pid: 41, name: /usr/bin/syncd]: 3459 messages lost due to rate-limiting

If everything is ok, we should not get those warnings that oid is not present in asic db, take a look at those logs, and here is my prediction what's happening:
Oct 13 06:33:25.561177 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 0 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x0 lagid:0x0 flags:0x1f446c flags2:0x0 lag:false
Oct 13 06:33:25.561177 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 1 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x5 lagid:0x0 flags:0x1f0440 flags2:0x0 lag:false
Oct 13 06:33:25.561177 str2-7050cx3-acs-01 WARNING syncd#syncd: :- check_fdb_event_notification_data: RID 0x1003a00000000 on SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID is not present on local ASIC DB
Oct 13 06:33:25.566333 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 0 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x0 lagid:0x0 flags:0x9f4440 flags2:0x0 lag:false
Oct 13 06:33:25.566333 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 1 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x1d lagid:0x0 flags:0x1f0440 flags2:0x0 lag:false
Oct 13 06:33:25.566952 str2-7050cx3-acs-01 WARNING syncd#syncd: :- check_fdb_event_notification_data: RID 0x1003a00000000 on SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID is not present on local ASIC DB
Oct 13 06:33:25.571290 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 0 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x0 lagid:0x0 flags:0x9f4464 flags2:0x0 lag:false
Oct 13 06:33:25.571290 str2-7050cx3-acs-01 INFO syncd#syncd: [0] SAI_API_FDB:_brcm_sai_fdb_event_cb:57 FDB event: 1 for mac 98-03-9B-03-22-00 vid:0x3e8, port:0x47 lagid:0x0 flags:0x1f0440 flags2:0x0 lag:false
Oct 13 06:33:25.571290 str2-7050cx3-acs-01 WARNING syncd#syncd: :- check_fdb_event_notification_data: RID 0x1003a00000000 on SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID is not present on local ASIC DB

As you can see mac address 98-03-9B-03-22-00 is jumping (assuming event 0 aged, and event 1 is learned  according to SAI brcm sdk) for many different ports,
I’m guessing here that value “port:0x0” is invalid value for port in brcm SAI internals, and that value is used to construct RID 0x1003a00000000, which came out to be invalid, this is my guess 

Of course this mac jumping doesn’t seem normal to me, unless this is what our test is doing, here is next question, this unittests where you see this jumping, what tests is exactly perform?

Next from sairedis .40 and .39, if we combine them, since they are continuation, we can see that .40 is ok, but it has fdb_flush api called:
2020-10-13.06:31:56.915366|f|SAI_OBJECT_TYPE_FDB_FLUSH:oid:0x21000000000000|
2020-10-13.06:32:06.370196|F|SAI_STATUS_SUCCESS

And right after that we can see flood of fdb_events with mac address: "98:03:9B:03:22:00”
2020-10-13.06:33:25.529600|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x2600000000060d\",\"mac\":\"98:03:9B:03:22:00\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a00000000061e"}]}]|
2020-10-13.06:33:25.547397|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x2600000000060d\",\"mac\":\"98:03:9B:03:22:00\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a000000000624"}]}]|
2020-10-13.06:33:25.562826|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x2600000000060d\",\"mac\":\"98:03:9B:03:22:00\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a00000000061a"}]}]|
2020-10-13.06:33:25.570081|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x2600000000060d\",\"mac\":\"98:03:9B:03:22:00\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a000000000616"}]}]|
…

Which is learned on ALL ports, we don’t see recording of AGED event, since in syslog we can see that AGED event contains invalid port number (my suspected 0x0 port)
And via entire sairedis.39 recording we can see start from:
2020-10-13.06:31:56.915366|f|SAI_OBJECT_TYPE_FDB_FLUSH:oid:0x21000000000000|
2020-10-13.06:32:06.370196|F|SAI_STATUS_SUCCESS
2020-10-13.06:33:25.529600|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x2600000000060d\",\"mac\":\"98:03:9B:03:22:00\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a00000000061e"}]}]|
And end on:
2020-10-13.06:34:53.090561|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x2600000000060d\",\"mac\":\"98:03:9B:03:22:00\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a000000000620"}]}]|

And there are 5422 events of learning this specific MAC on all ports, jumping all over the place all time, in my opinion, fdb flush triggered something ether with switch/asic itself on in SAI brcm sdk internally, since for this particular mac those notifications are generated constantly learned/aged for all bridge ports 

This will need investigation by Broadcom team what’s happening exactly 
Worth noticing that those fdb_event notifications start popping up after 1min and 19sec after flush
This is visible in recordings and syslog

From sairedis/syncd perspective there is nothing wrong
