### ISSUE TITLE
[ndppd] observing high cpu utilization 

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-buildimage#6823]
#### Description

ndppd is observed to be taking high cpu utilization when system is receiving significant control plane traffic

```
top - 23:05:43 up  8:44,  1 user,  load average: 6.04, 5.11, 4.63
Tasks: 281 total,   2 running, 245 sleeping,   0 stopped,  34 zombie
%Cpu(s): 20.4 us, 24.2 sy,  0.0 ni, 53.8 id,  0.1 wa,  0.0 hi,  1.4 si,  0.0 st
MiB Mem :   8026.8 total,   4625.0 free,   1829.6 used,   1572.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   5865.6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                       
 5139 root      20   0    5800   3688   3432 R 100.0   0.0  18:01.10 ndppd                                                                                                         
 4881 root      20   0 2039800 626552 108556 S  51.8   7.6  10:53.01 syncd                                                                                                         
 1165 root      20   0  227552  36436   6792 S  12.0   0.4  73:07.25 redis-server                                                                                                  
 4733 root      20   0  143116  47012  13464 S  12.0   0.6   4:01.89 python3       
```

#### Steps to reproduce the issue:
1. Execute top command on device running latest master
2.
3.

#### Output of `show version`:

```
(paste your output here)
```

**Comment by theasianpianist** [comment]
It looks like the root cause of this is `ndppd` loading IPv6 routes every 30 seconds: https://github.com/DanielAdolfsson/ndppd/blob/b8b2d401b9a83dae45776bb9fa95b1a5fe417d01/src/route.cc#L129

Because of all the routes announced by the T1s, the `/proc/net/ipv6_route` file is about 24k lines long. In `top`, `ndppd` CPU usage can be seen spiking every 30s (lasting for 7-8 seconds) which also corresponding with the debug logs generated on this line https://github.com/DanielAdolfsson/ndppd/blob/b8b2d401b9a83dae45776bb9fa95b1a5fe417d01/src/route.cc#L86

It does not look like there is a way to prevent `ndppd` from reading the IPv6 routes since that is part of its core feature set. However, there is theoretically a way to increase the polling interval so that the CPU spikes happen less frequently. The documentation is either out of date or incorrect, so I am investigating further along this avenue.

**Comment by theasianpianist** [comment]
After further investigation, the undocumented `route-ttl` configuration option can be used to change how frequently kernel IPv6 routes are read. Since this value is stored internally as a [signed integer](https://github.com/DanielAdolfsson/ndppd/blob/b8b2d401b9a83dae45776bb9fa95b1a5fe417d01/src/route.cc#L27), we can delay the CPU spikes to once every 2147483647ms (about 24 days) at most.
