### ISSUE TITLE
[DPB] config_db.json "BREAKOUT_CFG" update when upgrading

### ISSUE THREAD

**Issue by slutati1536** [Azure/sonic-buildimage#7402]
#### Description

when doing upgrade from image without DPB to image with DPB, 
the config_db.json file is not updated with "BREAKOUT_CFG" section.

when testing the upgrade scenario by:

1. installing 201911 vie onie
2. apply config_db.json file without BREAKOUT_CFG
3. upgraded to an image with DPB feature support with sonic-installer
4. the config_db.json was not updated with BREAKOUT_CFG, so the DPB feature will not work.

To clearify, the port configuration from the config_db.json (with any splits) is present on the switch with DPB image we upgraded to, the only issue is that without BREAKOUT_CFG section in the config_db.json, the user is not able to configure any new breakouts.

#### Steps to reproduce the issue:

1. installing 201911 vie onie
2. apply config_db.json file without BREAKOUT_CFG
3. upgraded to an image with DPB feature support with sonic-installer
4. the config_db.json was not updated with BREAKOUT_CFG, so the DPB feature will not work.

#### Describe the results you received:
 
the config_db.json was not updated with BREAKOUT_CFG section

#### Describe the results you expected:

the sonic installer should handel this issue in the case of sonic to sonic installation to a DPB image the config_db.json should be updated automatically.

#### Output of `show version`:

upgrade from SONiC-OS-201911.113-dirty-20210419.164156
to SONiC-OS-SONIC.dpb_master.3-9721ca85_Internal

**Comment by anshuv-mfst** [comment]
Issue triage 4/28: To be discussed in DPB subgroup.

**Comment by dprital** [comment]
@zhenggen-xu  - Can you please review this issue ?

**Comment by zhenggen-xu** [comment]
We did discuss this in the DPB subgroup meeting.  At this point, we are not automatically importing the "BREAKOUT_CFG" into configDB after upgrade,  instead we use "config reload -l" option to get the table.  If you strongly feel that is required,  please send a PR for importing  "BREAKOUT_CFG" into config_db.json in the migration scripts,  we know exactly the steps to get that table: ` sonic-cfggen -H -k <HWSKU> --var-json BREAKOUT_CFG`, and we can discuss that PR with community.

**Comment by robocoder99** [comment]
@zhenggen-xu After some discussion locally, we are okay with BREAKOUT_CFG not being imported by default, however we do believe that this case should be handled elegantly by `show interface breakout` and `config interface breakout` so that the end user is not faced with a Python traceback for a flow that we intend (user attempts to use breakout -> user runs `config reload -l`)

Something like `CONFIG_DB does not contain the required information to complete this action please run config reload -l to import this from the platform files to enable dynamic breakout features.` (Just an example)

Because this strays far enough away from the original intention of this issue I have raised a new one to handle this. (#7957)

**Comment by robocoder99** [comment]
Given this, this issue may be closed.
