### ISSUE TITLE
[202012] Build failure: marvell-armhf

### ISSUE THREAD

**Issue by dflynn-Nokia** [Azure/sonic-buildimage#7465]
#### Description

     The Azure.sonic-buildimage.official.marvell-armhf pipeline builds are failing with the following error.

    make[2]: Entering directory '/sonic/src/sonic-sairedis'
    Making install in meta
    make[3]: Entering directory '/sonic/src/sonic-sairedis/meta'
    make -C ../SAI/meta
    make[4]: Entering directory '/sonic/src/sonic-sairedis/SAI/meta'
    perl -I. parse.pl
    Processing capability file sample.cap
    Skipping cap file sample.cap
    Running Aspell
    Words to check: 2572
    ERROR: aspell error: Error: No word lists can be found for the language "en".
    [ ... ]
    [  FAIL LOG END  ] [ target/debs/buster/libsairedis_1.0.0_armhf.deb ]

The Nokia and Marvell development teams do not see this error when doing private builds.

#### Steps to reproduce the issue:
Build for the marvell-armhf platform

#### Describe the results you received:
Build failed with the above error.

#### Describe the results you expected:
Build succeeds

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anshuv-mfst** [comment]
HI @kcudnik - Could you please look into this issue, this is seen in Master and 202012 release. Build error is only seen in Azp (Nokia team didnt see this in their pvt build.)

**Comment by kcudnik** [comment]
seems like missing aspell-en in the build docker, but on 202012 branch this is explicitly installed here: https://github.com/Azure/sonic-buildimage/commit/2f8a5815f7

**Comment by dflynn-Nokia** [comment]
I am still unable to reproduce this problem in my private builds.
How best to make progress on this?

**Comment by kcudnik** [comment]
same here, on my local build i dont see this error, i think there is some difference when building local/az maybe in build images etc

**Comment by kcudnik** [comment]
There is issue with nroff on that latest image:

$ echo foo bar | /usr/bin/aspell  -l en -a
WARNING: Unable to enter Nroff mode: Unknown mode: "nroff".
Error: No word lists can be found for the language "en_US".

But after executing
# apt-get install --reinstall -y aspell-en

This error goes away and everything works fine
How sonicdev-microsoft.azurecr.io:443/sonic-slave-buster-march-armhf   latest is built ?
Since that reinstall is actually executed here: https://github.com/Azure/sonic-buildimage/blob/803e6d8b574873f1a4dd7ed8121fdebfbbbacb45/sonic-slave-buster/Dockerfile.j2#L368

**Comment by kcudnik** [comment]
it seems like reinstall is actually executed on build image but somehow has no effect?https://dev.azure.com/mssonic/build/_build/results?buildId=13430&view=logs&j=594b531d-901a-5eaa-0051-20781037afc4&t=2d2c06c2-f02c-5153-72fa-81e97e4a6a65&l=14667

**Comment by kcudnik** [comment]
hey @Sabareesh-Kumar-Anandan, you added original fix in commit 2f8a5815f7b38fd5d1b4d8d5f58aa4a9960a5863 https://github.com/Azure/sonic-buildimage/pull/6248 seems like this issue is back on latest image despite that fix is in place, would you have any tips on this one?

**Comment by kcudnik** [comment]
So this is interesting, since master build success, and /sonic-slave-buster/Dockerfile.j2 diff between origin202012 and master is not much, and not include any aspell changes:
```
$ git diff origin/202012 origin/master sonic-slave-buster/Dockerfile.j2
diff --git a/sonic-slave-buster/Dockerfile.j2 b/sonic-slave-buster/Dockerfile.j2
index 4b3e371f..e5f35f78 100644
--- a/sonic-slave-buster/Dockerfile.j2
+++ b/sonic-slave-buster/Dockerfile.j2
@@ -77,6 +77,7 @@ RUN apt-get update && apt-get install -y \
         dh-systemd \
         libzmq5 \
         libzmq3-dev \
+        jq \
# For quagga build
         libreadline-dev \
         texlive-latex-base \
@@ -301,6 +302,23 @@ RUN apt-get update && apt-get install -y \
         xsltproc \
         python-lxml \
         libexpat1-dev \
+# For WPA supplication
+        qtbase5-dev          \
+        aspell-en            \
+        libhiredis-dev       \
+        libnl-3-dev          \
+        swig3.0              \
+        libpython2.7-dev     \
+        libssl-dev           \
+        dbus                 \
+        libdbus-1-dev        \
+        libdbus-glib-1-2     \
+        libdbus-glib-1-dev   \
+        libreadline-dev      \
+        libncurses5-dev      \
+        libpcsclite-dev      \
+        docbook-to-man       \
+        docbook-utils        \
# For kdump-tools
         libbz2-dev \
# For linkmgrd
@@ -322,7 +340,13 @@ RUN apt-get update && apt-get install -y \
         libboost-regex1.71-dev \
         googletest \
         libgtest-dev \
-        libgcc-8-dev
+        libgcc-8-dev \
+# For sonic-host-services build
+        libcairo2-dev \
+        libdbus-1-dev \
+        libgirepository1.0-dev \
+        libsystemd-dev \
+        pkg-config

# Build fix for ARMHF buster libsairedis
{%- if CONFIGURED_ARCH == "armhf" %}
@@ -373,7 +397,7 @@ RUN export VERSION=1.14.2 \

RUN pip3 install --upgrade pip
RUN pip2 install --upgrade 'pip<21'
-RUN apt-get purge -y python-pip python3-pip
+RUN apt-get purge -y python-pip python3-pip python3-yaml
```
Master just add’s a bunch more packages also aspell-en, but reinstall is executed anyway and from pipeline log is installed:
https://dev.azure.com/mssonic/build/_build/results?buildId=13430&view=logs&j=594b531d-901a-5eaa-0051-20781037afc4&t=2d2c06c2-f02c-5153-72fa-81e97e4a6a65&l=14667

I added aspell-en to main package list in Dockerfile.j2:
https://github.com/Azure/sonic-buildimage/pull/7521

not sure if this will help, since when I build my sonic-slave-buster docker from scratch locally on clean origin/202012 I don’t have this issue, but somehow latest build on azure popeline sonicdev-microsoft.azurecr.io:443/sonic-slave-buster-march-armhf even that it contains aspell-en and reinstall command is execute, I can confirm that error still exits, not sure yet what is actual root cause here.

**Comment by kcudnik** [comment]
check this out:
```
$ docker run -it --privileged sonicdev-microsoft.azurecr.io:443/sonic-slave-buster-march-armhf:latest bash
root@f79ea7f1aabc:/# aspell -l en -a
WARNING: Unable to enter Nroff mode: Unknown mode: "nroff".
Error: No word lists can be found for the language "en".
root@f79ea7f1aabc:/# stat /usr/lib/aspell/en.
en.dat    en.multi
root@f79ea7f1aabc:/# stat /usr/lib/aspell/en.multi
  File: /usr/lib/aspell/en.multi
  Size: 83              Blocks: 8          IO Block: 4096   regular file
Device: 32h/50d Inode: 2376900     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-04-17 02:14:16.000000000 +0000
Modify: 2018-04-17 02:14:16.000000000 +0000
Change: 2021-05-04 15:10:15.281329058 +0000
 Birth: -
root@f79ea7f1aabc:/# aspell -l en -a
WARNING: Unable to enter Nroff mode: Unknown mode: "nroff".
Error: No word lists can be found for the language "en". // fail
root@f79ea7f1aabc:/# touch /usr/lib/aspell/en.multi
root@f79ea7f1aabc:/# aspell -l en -a
WARNING: Unable to enter Nroff mode: Unknown mode: "nroff".
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.7-20110707)  // works !
```

**Comment by dflynn-Nokia** [comment]
Trying this now on my PC.

Carl and I were also thinking this is related to readdir issue. See earlier email from Carl.
Still not sure why only seen in Azure pipeline builds.

Dennis

**Comment by kcudnik** [comment]
yes, thanks to Carl for pointer https://bugs.launchpad.net/qemu/+bug/1805913, and it still a bug, confirmed couple days ago,
and yes it's interesting that this is happening in azure pipelines, hmm, very interesting, since related to readdir and inode number, then maybe on azure pipeline host building docker slave have huge number of inodes? but after downloading docker to local host, inode numbers are updates, since that docker image is unpacked to new inode numbers are given locally, so maybe other inode attributes are somehow "too big" and truncated wrongly on readdir, or the files are listed in such order in that directory, so when readdir is listing dir, because of bug that en dictionary is not listed

**Comment by dflynn-Nokia** [comment]
I tried your sequence on my Linux desktop and see the same results you do.
Glad to have a way to test a fix for this without requiring Azure pipeline.

**Comment by kcudnik** [comment]
But don't know if this will actually work, since reinstall aspell-en touchces that directory anyway, so i propose to disable aspell on armhf since it's not that critical.

https://github.com/Azure/sonic-buildimage/pull/7550
https://github.com/Azure/sonic-buildimage/pull/7549

**Comment by kcudnik** [comment]
@dflynn-Nokia seems like builds are passing, and this workaround is working, can you confirm and close issue ?

**Comment by dflynn-Nokia** [comment]
Yes indeed, builds are now working.
Thanks for all you help with this!
