### ISSUE TITLE
[PDDF]Does PDDF support CPLDs with the same device address and different bus numbers?

### ISSUE THREAD

**Issue by kidoflamancha** [Azure/sonic-buildimage#7606]
#### Description

I have a device that controls different line cards through CPLD, each CPLD has the same address but different bus numbers. Does PDDF support this situation?
It is known from the code that PDDF stores all CPLDs in the linked list and only matches the device address when using it. Why doesn't it match the bus number or device name?

#### Steps to reproduce the issue:
NA

#### Describe the results you received:
```c
int board_i2c_cpld_read(unsigned short cpld_addr, u8 reg)
{
	struct list_head   *list_node = NULL;
	struct cpld_client_node *cpld_node = NULL;
	int ret = -EPERM;
	
	//hw_preaccess_func_cpld_mux_default((uint32_t)cpld_addr, NULL);

	mutex_lock(&list_lock);

	list_for_each(list_node, &cpld_client_list)
	{
		cpld_node = list_entry(list_node, struct cpld_client_node, list);
		
		if (cpld_node->client->addr == cpld_addr) {
			ret = i2c_smbus_read_byte_data(cpld_node->client, reg);
			break;
		}
	}
	
	mutex_unlock(&list_lock);

	return ret;
}
EXPORT_SYMBOL(board_i2c_cpld_read);
```

#### Describe the results you expected:

Add matching of bus number or device name, or use hash table?

**Comment by anshuv-mfst** [comment]
@adyeung - can you please take a look, thanks. 
@kidoflamancha - what is the device used?

**Comment by fk410167** [comment]
@kidoflamancha 

The i2c device creation part is okay in case of CPLDs with same addresses but different buses. However, if you want to use the APIs, board_i2c_cpld_read() and board_i2c_cpld_write(), they can fetch wrong values due to the i2c-client linked-list stored in the driver.
PDDF framework stores the i2c clients created in a hashtable against the object names in the pddf-device.json files. This can be utilised to retrieve the correct 'i2c-client'. Base APIs i2c_smbus_read_byte_data() and i2c_smbus_write_byte_data() can be used.

**Comment by kidoflamancha** [comment]
> @kidoflamancha
> 
> The i2c device creation part is okay in case of CPLDs with same addresses but different buses. However, if you want to use the APIs, board_i2c_cpld_read() and board_i2c_cpld_write(), they can fetch wrong values due to the i2c-client linked-list stored in the driver.
> PDDF framework stores the i2c clients created in a hashtable against the object names in the pddf-device.json files. This can be utilised to retrieve the correct 'i2c-client'. Base APIs i2c_smbus_read_byte_data() and i2c_smbus_write_byte_data() can be used.

Thank you for your help, I found that I can customize the do_get() function. This issue can be closed.
