### ISSUE TITLE
[DPB] DPB falls cause of invalid value in "has_global_scope" element

### ISSUE THREAD

**Issue by mykolaxgerasymenko** [Azure/sonic-buildimage#9326]
#### Description
The Dynamic Port Breakout feature is not working as expected on the latest master image

#### Steps to reproduce the issue:
1. `sudo config interface breakout Ethernet0 4x100G[50G] -f`

**NOTE:**
To reproduce this issue, a following PRs that fix other issues in SONiC should be merged into master:
1) Azure/sonic-buildimage/pull/9075
2) Azure/sonic-buildimage/pull/9276
#### Describe the results you received:
```
admin@sonic:~$ sudo config interface breakout Ethernet192 4x100G[50G] -f
Do you want to Breakout the port, continue? [y/N]: y

Running Breakout Mode : 1x400G[200G] 
Target Breakout Mode : 4x100G[50G]

Ports to be deleted : 
 {
    "Ethernet192": "400000"
}
Ports to be added : 
 {
    "Ethernet192": "100000",
    "Ethernet194": "100000",
    "Ethernet196": "100000",
    "Ethernet198": "100000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet192": "400000"
} 
Final list of ports to be added :  
 {
    "Ethernet192": "100000",
    "Ethernet194": "100000",
    "Ethernet196": "100000",
    "Ethernet198": "100000"
}

Note: Below table(s) have no YANG models:
KDUMP, SNMP, SNMP_COMMUNITY, 
libyang[0]: Invalid value "False" in "has_global_scope" element. (path: /sonic-feature:sonic-feature/FEATURE/FEATURE_LIST[name='bgp']/has_global_scope)
sonic_yang(3):Data Loading Failed:Invalid value "False" in "has_global_scope" element.
Data Loading Failed
Invalid value "False" in "has_global_scope" element.
ConfigMgmt Class creation failed
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed
```
#### Describe the results you expected:
config interface breakout should work without errors

#### Output of `show version`:
For testing, I manually built the sonic-image 15 November 2021 with last commits on the sonic-buildimage master and resolved issues which I mentioned in "NOTE" to "Steps to reproduce the issue".

**Comment by tw0byt3** [comment]
@mykolaxgerasymenko Facing this issue on Mellanox SN2700 after resolving the issues mentioned in the NOTE. I observed that in sonic-feature.yang under /src/sonic-yang-models/yang-models, leaf "has_global_scope" has a type **boolean** and the default is **false**, yet it is considered as an Invalid value.

**Comment by mykolaxgerasymenko** [comment]
@tw0byt3, I tried adding boolean as typedef in sonic-feature.yang and it works correctly. 
But your advice (adding boolean as typedef under sonic-types.yang.j2) seems to be better, because after fixing this issue, there will be another issue with the same cause (boolean types in different literal case), but in a different yang model.
Now I am trying your suggestion, test it and open PR.

**Comment by mykolaxgerasymenko** [comment]
The PR for fix this issue has been opened:
[DPB][YANG] Fix cases when boolean is used in different literal cases
https://github.com/Azure/sonic-buildimage/pull/9418

**Comment by tw0byt3** [comment]
@mykolaxgerasymenko After the fix of this is done, the breakout fails due to the CRM yang model. I tried to accommodate the changes required. Post that, this is the error I am facing.

root@localhost:~# config interface breakout Ethernet0 4x10G[25G]
Do you want to Breakout the port, continue? [y/N]: y

Running Breakout Mode : 1x100G[50G,40G,25G,10G]
Target Breakout Mode : 4x10G[25G]

Ports to be deleted :
{
"Ethernet0": "100000"
}
Ports to be added :
{
"Ethernet0": "10000",
"Ethernet1": "10000",
"Ethernet2": "10000",
"Ethernet3": "10000"
}

After running Logic to limit the impact

Final list of ports to be deleted :
{
"Ethernet0": "100000"
}
Final list of ports to be added :
{
"Ethernet0": "10000",
"Ethernet1": "10000",
"Ethernet2": "10000",
"Ethernet3": "10000"
}
Note: Below table(s) have no YANG models:
KDUMP, SNMP, SNMP_COMMUNITY, XCVRD_LOG,
Below Config can not be verified, It may cause harm to the system
{}
Do you wish to Continue? [y/N]: y
Create Config to load in DB, Failed
'str' object has no attribute 'append'
Config Diff Generation failed
'str' object has no attribute 'append'
'str' object has no attribute 'append'
Port Deletion Failed
[ERROR] Port breakout Failed!!! Opting Out
Failed to break out Port. Error:

Can someone help me identity there is this str object?

**Comment by zhangyanzhao** [comment]
PR need be merged
